Repository Team-Formation-Lap/Backend, pull requests merged in 2025-04, with the labels that each got.

#52 [Feat/#51] 이력서 삭제 api 구현
  resume/urls.py
  resume/views.py
Labels: Feat

#54 [feat/#53] 면접결과 리스트 조회 API 구현
  result/urls.py
  result/views.py
Labels: Feat

#56 [feat/#55] 면접결과 내용 조회 api 구현
  result/urls.py
  result/views.py
Labels: Feat

#58 [Feat/#48] 로그인 API 구현
  apps/settings.py
  apps/urls.py
  interview/serializers.py
  interview/views.py
  requirements.txt
  result/views.py
  resume/views.py
  user/authentication.py
  user/backends.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: Feat, Fix

#59 [fix/#57] 면접결과 전체조회 api 수정
  result/models.py
  result/views.py
Labels: Fix

#62 [fix/#61] :이력서 업로드 api 오류 수정
  resume/urls.py
  resume/views.py
Labels: Fix

#67 [feat/#66] JWT 토큰적용 추가
  result/urls.py
  result/views.py
  resume/views.py
Labels: Feat

#71 [Fix/#70]:면접 시작 api 수정
  interview/serializers.py
  interview/views.py
Labels: Fix

#73 [fix/#72] 면접결과 삭제 api 수정
  result/urls.py
  result/views.py
Labels: Fix

#74 [feat/#69] 행동분석 코드 추가
  interview/utils.py
Labels: Feat

#76 [Fix/#70] 피드백 프롬프팅 개선
  interview/tasks.py
Labels: Fix
