Repository Team-Formation-Lap/Backend, pull requests merged in 2025-02, with the labels that each got.

#2 [chore/#1] 개발 환경 세팅
  .gitignore
  Dockerfile
  README.md
  apps/__init__.py
  apps/asgi.py
  apps/settings.py
  apps/urls.py
  apps/wsgi.py
  docker-compose.yml
  interview/__init__.py
  interview/admin.py
  interview/apps.py
  interview/models.py
  interview/tests.py
  interview/views.py
  manage.py
  member/__init__.py
  member/admin.py
  member/apps.py
  member/models.py
  member/tests.py
  member/views.py
  requirements.txt
  result/__init__.py
  result/admin.py
  result/apps.py
  result/models.py
  result/tests.py
  result/views.py
  resume/__init__.py
  resume/admin.py
  resume/apps.py
  resume/models.py
  resume/tests.py
  resume/views.py
Labels: Chore

#4 [feat/#3] 도메인 별 엔티티 정의
  .gitignore
  apps/settings.py
  interview/models.py
  member/models.py
  result/models.py
  resume/models.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Feat

#6 [chore/#5] .gitignore 수정
  .gitignore
Labels: Chore

#8 [chore/#7].gitignore 수정
  interview/migrations/__init__.py
  result/migrations/__init__.py
  resume/migrations/__init__.py
  user/migrations/__init__.py
Labels: Chore

#12 [feat/#9] 회원가입 API 구현
  apps/settings.py
  apps/urls.py
  requirements.txt
  user/admin.py
  user/serializers.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Feat

#14 [feat/#13] 이력서 업로드 API 구현
  apps/settings.py
  apps/urls.py
  resume/permission.py
  resume/serializers.py
  resume/urls.py
  resume/views.py
  user/urls.py
Labels: Feat

#16 [feat/#11] 웹소켓 연결 구현
  apps/asgi.py
  apps/settings.py
  docker-compose.yml
  gpt/__init__.py
  gpt/admin.py
  gpt/apps.py
  gpt/consumers.py
  gpt/models.py
  gpt/routing.py
  gpt/tests.py
  gpt/views.py
  requirements.txt
Labels: Feat

#18 [feat/#17] Celery & RabbitMQ 환경 구축
  apps/celery.py
  apps/settings.py
  docker-compose.yml
  requirements.txt
Labels: Feat

#20 [feat/#15] 결과(영상) 업로드 API / 미디어 파일 S3 url 설정
  apps/settings.py
  apps/urls.py
  requirements.txt
  result/permission.py
  result/serializers.py
  result/urls.py
  result/views.py
Labels: Feat

#22 fix: 미로그인 예외처리 기능삭제
  resume/permission.py
  resume/urls.py
  resume/views.py
Labels: Fix

#24 [fix/#23] 미로그인 예외처리 기능삭제
  result/permission.py
  result/urls.py
  result/views.py
Labels: Fix

#26 fix:CORS 에러 해결
  apps/settings.py
  requirements.txt
Labels: Fix

#28 [fix] CORS 에러 설정 수정
  apps/settings.py
Labels: Fix

#33 [feat/32]:STT 구현
  interview/consumers.py
  interview/tasks.py
Labels: Feat

#37 [feat/#36]: 면접 결과 생성 api 구현
  interview/tasks.py
  interview/urls.py
  interview/views.py
Labels: Feat

#39 [feat/#38]:행동 분석 api 구현
  Dockerfile
  interview/urls.py
  interview/utils.py
  interview/views.py
  requirements.txt
  result/models.py
Labels: Feat

#41 [fix/40]: 면접 영상 s3 저장 경로 수정
  result/views.py
Labels: Fix

#43 [fix/#42]:STT 오류 수정 완료
  interview/consumers.py
  interview/tasks.py
Labels: Fix
